Remove superfluous indents
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #186
Opened 2020-11-02 16:21 UTC by sypets

2020-11-02 16:26 UTC, mbrodala requested changes

2020-11-02 16:26 UTC, mbrodala commented on Documentation/Appendix/CommitMessage.rst
> +.. important::
This should stay at the original location and have only the indentation stripped.

2020-11-02 16:26 UTC, mbrodala commented on Documentation/Appendix/CommitMessage.rst
> --  Keep the whole line below 52 characters if possible, but below 80 in any case
This and below also looks like way more change than necessary ...

2020-11-02 16:26 UTC, mbrodala commented on Documentation/CheatSheets/RunTestsWithoutDocker.rst
> +Run tests (without Docker) cheat sheet
Why this file?

2020-11-02 17:41 UTC, sypets commented on Documentation/CheatSheets/RunTestsWithoutDocker.rst
> +Run tests (without Docker) cheat sheet
This should not have been in there - is removed.

2020-11-02 17:49 UTC, sypets commented on Documentation/Appendix/CommitMessage.rst
> --  Keep the whole line below 52 characters if possible, but below 80 in any case
I changed the order - the problem was the bullet points and the - indented text after. The indents were sometimes used to group things together - here the content related to "imperative mood" - if the indents are just removed this "grouping" is lost and it might make it more difficult to read.

Changed it back now.

2020-11-03 07:41 UTC, mbrodala commented on Documentation/Appendix/CommitMessage.rst
> --  Keep the whole line below 52 characters if possible, but below 80 in any case
I see, thanks for going deep into this. Let's use this as it is for now and do optimizations in another change.

2020-11-03 07:42 UTC, mbrodala approved these changes

2020-11-03 07:42 UTC, merged