[TASK] Update TYPO3 repository URL
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #208
Opened 2021-08-02 15:35 UTC by alexander-nitsche

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.

2021-08-05 09:08 UTC, susannemoog commented on Documentation/Appendix/Windows/GitForWindows.rst
> +git config --global url."ssh://<username>@review.typo3.org:29418/Packages/TYPO3.CMS.git"
Does this set just the PUSH Url or does it set both pull and push? With pushInsteadOf that was only relevant to push, but I think to change the push url only the command itself needs to be adjusted.

2021-08-05 09:10 UTC, susannemoog commented on Documentation/Appendix/Windows/GitForWindows.rst
> +git config --global url."ssh://<username>@review.typo3.org:29418/Packages/TYPO3.CMS.git"
(additionally: restricting this globally to TYPO3.CMS might not be a good idea, as there have been - and maybe still are - other projects using Gerrit)

2021-08-05 09:10 UTC, susannemoog requested changes
see single comments

2021-08-05 10:37 UTC, alexander-nitsche commented on Documentation/Appendix/Windows/GitForWindows.rst
> +git config --global url."ssh://<username>@review.typo3.org:29418/Packages/TYPO3.CMS.git"
I guess i just aligned it with https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/205/files#diff-ab8c729c7a5a0fdf344ff1e9c4752b3b50e59a537628cd54b5cd173d17e5739eR140 . Did not test it really.

2021-08-05 10:51 UTC, susannemoog commented on Documentation/Appendix/Windows/GitForWindows.rst
> +git config --global url."ssh://<username>@review.typo3.org:29418/Packages/TYPO3.CMS.git"
check the link you posted: there is `git config remote.origin.pushurl` for gerrit - I guess this is what we need here.

2021-08-09 18:51 UTC, alexander-nitsche commented on Documentation/Appendix/Windows/GitForWindows.rst
> +git config --global url."ssh://<username>@review.typo3.org:29418/Packages/TYPO3.CMS.git"
hi susi, what if you would update the commit? i do not feel comfortable enough in the gerrit area ..

2021-08-17 08:58 UTC, susannemoog approved these changes

2021-08-17 08:58 UTC, merged