Update SettingUpTypo3Ddev.rst
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #216
Opened 2021-09-30 16:40 UTC by joworeiter

remove the "Clone TYPO3" Section from docs since you dont need to clone the typo3 repo if you use ddev .

2021-09-30 16:48 UTC, gilbertsoft commented
This guide is about the contribution to the core where you ofc have to clone the repo!

2021-09-30 16:49 UTC, gilbertsoft requested changes
This guide is about the contribution to the core where you ofc have to clone the repo!

2021-10-01 08:11 UTC, jonaseberle commented
This page ranks extremely (too ;) ) well with a Google search for `typo3 ddev`. 
I would suggest a notice there like "This is the setup you'll need for TYPO3 Core contribution. If you are looking for a normal setup, see https://ddev.readthedocs.io/en/stable/users/cli-usage/#typo3-quickstart"

@joworeiter would you like to do that?

2021-10-01 08:27 UTC, joworeiter commented
@jonaseberle I just wanted to setup a new TYPO3 project. Actually I overlooked that i landed on the core contribution page. 
Therefore I would be greate to put a disclaimer on top, with the link to the quickstart page.

2021-10-01 15:06 UTC, gilbertsoft commented
> 
> 
> This page ranks extremely (too ;) ) well with a Google search for `typo3 ddev`. I would suggest a notice there like "This is the setup you'll need for TYPO3 Core contribution. If you are looking for a normal setup, see https://ddev.readthedocs.io/en/stable/users/cli-usage/#typo3-quickstart"
> 
> @joworeiter would you like to do that?

Check the warning I've added some time ago at the top!

2021-10-01 15:10 UTC, joworeiter commented
so, no more things to do, except starting reading on the top ;)

2021-10-01 15:10 UTC, closed without merging

2021-10-01 15:11 UTC, mbrodala commented
@gilbertsoft What about changing the headline? Something like:

### TYPO3 core contribution setup with DDEV

2021-10-01 16:02 UTC, gilbertsoft commented
> 
> 
> @gilbertsoft What about changing the headline? Something like:
> ### TYPO3 core contribution setup with DDEV

Yeah, maybe that's read then :D

2021-10-01 16:07 UTC, gilbertsoft commented
Here we go https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/217