utf8 is deprecated, utf8mb4_0900_ai_ci is recommended
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #234
Opened 2021-12-29 09:47 UTC by masi

Use the newer one utf8mb4 which covers all UTF8 codepoints. utf8mb3 does not, so eg Emojis cannot be stored.

2021-12-29 10:09 UTC, sypets requested changes
Thank you for your PR! That is very helpful.

I have some minor nitpicks (spelling) and some things where it might be helpful to change your suggestions slightly. If you have time, can you make the adjustments?

If not, please let us know and someone else can take care of it. Thanks.

2021-12-29 10:09 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> +   mysql> CREATE DATABASE t3coredev CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
We could also double-check in core: typo3/sysext/core/Classes/Database/Platform/PlatformInformation.php

This also uses utf8mb4, but not the collation. Can you point me to a code-snippet where this is confirmed?

In the file typo3/sysext/install/Classes/Controller/InstallerController.php `'collate' => 'utf8mb4_unicode_ci'` is used.

2021-12-29 10:09 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> +   For Mysql versions lower than 8.0 or MariaDB use the collation utf8mb4_general_ci.
> Mysql

MySQL

2021-12-29 10:09 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> +   For Mysql versions lower than 8.0 or MariaDB use the collation utf8mb4_general_ci.
For MariaDB, you can also use utf8mb4: https://mariadb.com/kb/en/supported-character-sets-and-collations/

While you only mention the collation here, this might be misledading.

Maybe just advise to use utf8mb4 where supported.

2021-12-29 16:12 UTC, masi commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> +   For Mysql versions lower than 8.0 or MariaDB use the collation utf8mb4_general_ci.
I didn't mention the encoding specifically as utf8mb4 is supported by all compatible versions of MySQL and MariaDB. Although I'm not sure about Mariadb as typo3.org gives no version specifics except for MySQL.

2021-12-29 16:14 UTC, masi commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> +   mysql> CREATE DATABASE t3coredev CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
The docs for 8.0 say that utf8mb4_0900_ai_ci is the vendor default. I assume TYPO3 sets the collation to have a consistent result across installations with locally changed defaults.

2022-02-21 16:23 UTC, sypets approved these changes

2022-02-21 16:28 UTC, merged