Update DDEV documentation: set PHP version
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #235
Opened 2022-01-02 13:19 UTC by sypets

2022-01-02 15:41 UTC, brotkrueml requested changes

2022-01-02 15:41 UTC, brotkrueml commented on Documentation/Appendix/SettingUpTypo3Ddev.rst
> +In order to be able to use Composer inside DDEV::
This is not needed (anymore). Composer 2 is the default in the current ddev version:
https://ddev.readthedocs.io/en/stable/users/developer-tools/#ddev-and-composer
And composer is available without setting a version.

2022-01-02 15:41 UTC, brotkrueml commented on Documentation/Appendix/SettingUpTypo3Ddev.rst
> +Set correct PHP version for latest "main" development branch::
I would prefer: "Set the PHP version". By now, 7.4, 8.0 and 8.1 are "correct".

2022-01-03 08:55 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Ddev.rst
> +Set correct PHP version for latest "main" development branch::
I used 8.1 now and wrote "for example" to make it clear it is just an example (and may not always get updated right away in the future).

2022-01-05 07:02 UTC, susannemoog approved these changes

2022-01-05 07:02 UTC, merged