Add commands with runTests.sh for building
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #265
Opened 2022-05-21 11:05 UTC by sypets

Add the commands for building with runTests.sh:

- runTests.sh -s composerInstall
- runTests.sh -s buildCss
- runTests.sh -s buildJavascript

The section on yarn was removed in the setup section. It is not
necessary to build the assets when setting up. It is only necessary
when changing SCSS or Typescript / JavaScript etc. Additionally,
it is planned to have a section with all build commands in the
Howto section. This makes it more appropriate to remove the part
in the setup section.

For all listed commands, we add TABs so that we can always show
the runTests.sh commands and the "direct commands" side by side.

This will hopefully make it less confusing for the readers.

It was also discussed to remove the direct commands entirely - however
there is sometimes still the need to use the direct command. In any
case it is always noted that runTests.sh is recommended.

Resolves: #249
Resolves: #254

2022-05-21 15:45 UTC, jonaseberle requested changes

2022-05-21 15:45 UTC, jonaseberle commented on Documentation/Appendix/SettingUpTypo3Ddev.rst
> +need the direct commands, you are encouraged to check look them up yourself
```suggestion
need the direct commands, you are encouraged to look them up
```

2022-05-21 15:45 UTC, jonaseberle commented on Documentation/Appendix/SettingUpTypo3Ddev.rst
> +The following is not necessary for the initial build, but once you change some assets (e.g.
I can't say for sure. But I think to remember we wanted to use "for example" preferably over "e.g.".
```suggestion
The following is not necessary for the initial build, but once you change some assets (for example
```

2022-05-21 15:46 UTC, jonaseberle commented
Thank you!

2022-05-23 07:31 UTC, jonaseberle submitted a review, later dismissed

2022-05-23 08:41 UTC, sypets commented
Will fix conflicts and the double colons ...

2022-05-24 12:58 UTC, jonaseberle approved these changes

2022-06-02 09:59 UTC, jonaseberle approved these changes

2022-06-02 10:00 UTC, jonaseberle approved these changes

2022-06-02 10:08 UTC, mbrodala approved these changes

2022-06-02 10:08 UTC, merged