Remove reference to htdocs directory
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #300
Opened 2023-02-08 17:37 UTC by sypets

We are in a core setup installation. We don't have a htdocs or public directory.

2023-02-09 05:35 UTC, linawolf requested changes
So what would you call the main directory here? Just removing the sentence is not helpfull

2023-02-09 07:28 UTC, sypets commented
If following the workflow, we are already in the right directory. (/var/www/t3coredev). So we could either just leave out the question of the directory, or use the same one as in https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/Git/Index.html :

`cd /var/www/t3coredev`

https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/SettingUpTypo3Manually.html

I will push an update

2023-02-10 17:44 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> -In your htdocs directory:
> I would like to keep the info what directory we are in here. People sometimes don't read a complete page but only the section that is currently important.

fully agree. Though it might be awkward if information is repeated. Good to find a middle ground.

I had a look at the other code snippets with _bash_ or _shell_. Sometimes the path is included in that.  Most of the time it is just "shell command").

Might also be a good idea to have a "best practice" for that. 

I have pushed another solution were the path is in the caption. I also fixed the code-block syntax in previous version and used lexer "mysql" for mysql commands.

`grep -r -E -A 2 "\.\. code-block:: (bash|shell)" */Documentation  | grep caption`

Please have another look @linawolf

2023-02-10 17:48 UTC, sypets commented on Documentation/Appendix/SettingUpTypo3Manually.rst
> -In your htdocs directory:
(The additional indents are because I now made the additional changes locally with PhpStorm and it uses the .editorconfig with 4 spaces.) - Initial change I made with "Edit on GitHub" - not really the best option usually.

2023-02-11 07:59 UTC, linawolf approved these changes

2023-02-11 07:59 UTC, merged