[TASK] Address recent Coding Standards
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #329
Opened 2024-02-15 11:34 UTC by garvinhicking

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/4011

2024-02-15 11:46 UTC, linawolf approved these changes

2024-02-15 18:53 UTC, brotkrueml requested changes

2024-02-15 18:53 UTC, brotkrueml commented on Documentation/Appendix/Cgl.rst
> +(which follows PHP-FIG, PSR-1/PSR-2 and PSR-12 at the time of this writing),
Actually, it is PER-CS1.0 (which is identical to PSR-12) with quite some additions towards PER-CS2.0 in Core:
https://github.com/TYPO3/typo3/blob/main/Build/php-cs-fixer/config.php

2024-02-15 18:53 UTC, brotkrueml commented on Documentation/Appendix/IdePhpStormSetup.rst
> +However, you can use the following PhpStorm code style to comply with PSR-12, which
As above, PER-CS1.0 with additions. AFAIK PhpStorm can be configured to use the php-cs-fixer configuration file (PHP > Quality > PHP CS Fixer, or similar).

2024-02-15 18:53 UTC, brotkrueml commented on Documentation/Appendix/IdePhpStormSetup.rst
> +Choose :guilabel:`PSR-12`.
As above, the configuration of php-cs-fixer should be used directly.

2024-02-15 18:53 UTC, brotkrueml commented on Documentation/Setup/SetupIde.rst
> +setup your Editor / IDE to use PSR-12 (recommended at the time of this
Like above, PERCS-1.0 with additions.

2024-02-16 12:46 UTC, garvinhicking commented
@brotkrueml  I've rephrased this to try to better indicate the changing standards and be more abstract.

2024-02-16 17:55 UTC, brotkrueml commented on Documentation/Appendix/Cgl.rst
> +Make sure you are using the correct PHP codestyle. It is based on
```suggestion
Make sure you are using the correct PHP code style. It is based on
```

2024-02-16 17:57 UTC, brotkrueml commented on Documentation/Appendix/IdePhpStormSetup.rst
> +For a quick start, you can Howevern use the following PhpStorm code
```suggestion
For a quick start, you can use the following PhpStorm code
```

2024-02-16 17:58 UTC, brotkrueml commented on Documentation/Setup/SetupIde.rst
> +setup your Editor / IDE to use the recommendation as described in the
```suggestion
setup your editor / IDE to use the recommendation as described in the
```

2024-02-16 17:58 UTC, brotkrueml approved these changes

2024-02-16 18:08 UTC, merged