[TASK] Rework smaller parts to add specific notes
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #339
Opened 2024-06-26 12:23 UTC by garvinhicking

(This may use some :ref: links which are committed seperately)

2024-06-26 12:50 UTC, sbuerk requested changes

2024-06-26 12:50 UTC, sbuerk commented on Documentation/Appendix/HowToDeprecateThings.rst
> +    It's not always possible to "deprecate" everything. In some cases,
missing empty line ? :thinking:

2024-06-26 12:50 UTC, sbuerk commented on Documentation/Appendix/OSX/InstallGrunt.rst
> +   You may not need this at all, if you are using :ref:`runTests.sh <runtests_sh>`
alignment - 3 spaces vs 4 spaces ?

2024-06-26 12:50 UTC, sbuerk commented on Documentation/Appendix/OSX/InstallGrunt.rst
>  In your Terminal app navigate to the folder that you cloned the TYPO3 source into. Switch into the ``Build`` folder and run
Unrelated to this pr, but are double ticks (start + end paired) okay ? In TYPO3 we usualy use single ticks (vs doctrine for example).

2024-06-26 12:50 UTC, sbuerk commented on Documentation/Appendix/OSX/InstallNpm.rst
> +   You may not need this at all, if you are using :ref:`runTests.sh <runtests_sh>`
Alignment 3 vs 4 spaces

2024-06-26 12:50 UTC, sbuerk commented on Documentation/CheatSheets/Git.rst
>     Pushing to `refs/publish` is deprecated, we now push to `refs/for`.
missing empty line ?

2024-06-26 14:07 UTC, linawolf commented on Documentation/Appendix/HowToDeprecateThings.rst
> +    It's not always possible to "deprecate" everything. In some cases,
There is not rule about this and all combinations work.

2024-06-26 14:08 UTC, linawolf commented on Documentation/Appendix/OSX/InstallGrunt.rst
>  In your Terminal app navigate to the folder that you cloned the TYPO3 source into. Switch into the ``Build`` folder and run
The only difference in our implementation is that you can use a single backtick within double backticks without escaping

2024-06-26 14:37 UTC, garvinhicking commented on Documentation/Appendix/OSX/InstallGrunt.rst
> +   You may not need this at all, if you are using :ref:`runTests.sh <runtests_sh>`
This is generally something left to clean-up, I would prefer to do this in a seperate PR

2024-06-26 16:40 UTC, linawolf submitted a review, later dismissed

2024-06-27 14:08 UTC, froemken commented on Documentation/Appendix/HowToDeprecateThings.rst
> +    hard breaking changes must be introduced. These need to be adressed
```suggestion
    hard breaking changes must be introduced. These need to be addressed
```

2024-06-27 14:11 UTC, froemken commented on Documentation/ReportingAnIssue/Index.rst
> +to triage, the more time we have for actually adressing bugs and features.
```suggestion
to triage, the more time we have for actually addressing bugs and features.
```

2024-06-28 21:56 UTC, sbuerk approved these changes

2024-06-28 21:56 UTC, merged