[TASK] Rework chapter about the runTests.sh and build/testing mechanism
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #340
Opened 2024-06-26 12:32 UTC by garvinhicking

2024-06-26 12:38 UTC, garvinhicking commented on Documentation/HandlingAPatch/CherryPick.rst
> +   `git reset`` performed after that would delete local changes, which
```suggestion
   `git reset` performed after that would delete local changes, which
```

2024-06-26 13:04 UTC, sbuerk requested changes

2024-06-26 14:39 UTC, garvinhicking commented on Documentation/Testing/CoreTesting.rst
> +Compared to your local execution tt's just that the combinations of tests
ack, done

2024-06-27 14:19 UTC, froemken commented on Documentation/Testing/CoreTesting.rst
> +SQLite instead, due to less depndencies). All in one network. It then then starts a PHP 8.2 container and calls
```suggestion
SQLite instead, due to less dependencies). All in one network. It then starts a PHP 8.2 container and calls
```

2024-06-27 14:21 UTC, froemken commented on Documentation/Testing/CoreTesting.rst
> +starts the containers it needs: Redis, memcached (previosuly also MariaDB by default, which is now using
```suggestion
starts the containers it needs: Redis, memcached (previously also MariaDB by default, which is now using
```

2024-06-27 14:23 UTC, froemken commented on Documentation/Testing/CoreTesting.rst
> +Let's verify our PhpStorm debug settings first. Go to :guilabel:`File > Settings > Languages & Frameworks > PHP
Is that a typo `&_`? Don't know that writing.

2024-06-27 14:25 UTC, froemken commented on Documentation/Testing/CoreTesting.rst
> +    TYPO3 core test runner. Execute acceptance, unit, functional and other test suites in
```suggestion
    TYPO3 Core test runner. Execute acceptance, unit, functional and other test suites in
```

2024-06-27 15:12 UTC, garvinhicking commented on Documentation/Testing/CoreTesting.rst
> +Let's verify our PhpStorm debug settings first. Go to :guilabel:`File > Settings > Languages & Frameworks > PHP
That was just an error, thanks!

2024-06-28 21:53 UTC, sbuerk approved these changes

2024-06-28 21:55 UTC, merged