[TASK] Add a "Quick start" tutorial for contributors (DevDays)
TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow pull request #345
Opened 2024-06-29 23:40 UTC by garvinhicking

2024-06-29 23:42 UTC, garvinhicking commented
**Note: I couldn't get the "EXT:styleguide" Frontend Pagetree to work with this DDEV setup. Don't know if it's a bug in the styleguide setup, or a problem with ddev.**

2024-07-02 19:27 UTC, froemken commented on Documentation/Quickstart/1-Preqrequisites.rst
> +.. _quickstart-prerequisites:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Prerequisites

..  _quickstart-prerequisites:
```

2024-07-02 19:35 UTC, froemken commented on Documentation/Quickstart/1-Preqrequisites.rst
> +    neccessarily need a GitHub account.
```suggestion
    This guide uses the *https* method to connect to GitHub, so you do not
    need to have a GitHub account.
```

2024-07-02 19:36 UTC, froemken commented on Documentation/Quickstart/1-Preqrequisites.rst
> +    you should already use something like PhpStorm, Visual Studeio Code, vi(m)...
```suggestion
    you should already use something like PhpStorm, Visual Studio Code, vi(m)...
```

2024-07-02 19:38 UTC, froemken commented on Documentation/Quickstart/2-Accounts.rst
> +.. _quickstart-accounts:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Accounts

..  _quickstart-accounts:
```

2024-07-02 19:42 UTC, froemken commented on Documentation/Quickstart/2-Accounts.rst
> +    your SSH public key here. See :ref:`GerritAccount`.
Two `here` in one sentence. What about?

```suggestion
    First login via the `My TYPO3` SSO account. Afterwards you need to upload
    your SSH public key here. See :ref:`GerritAccount`.
```

2024-07-02 19:43 UTC, froemken commented on Documentation/Quickstart/3-Git.rst
> +.. _quickstart-git:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Git repository

..  _quickstart-git:
```

2024-07-02 19:46 UTC, froemken commented on Documentation/Quickstart/4-DDEV.rst
> +.. _quickstart-ddev:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: DDEV

..  _quickstart-ddev:
```

2024-07-02 19:48 UTC, froemken commented on Documentation/Quickstart/4-DDEV.rst
> +        chdir ~/TYPO3-Contribute
I have never ever worked with `chdir`. Either on Mac, nor on Linux nor on Windows. Just `cd`.

2024-07-02 19:50 UTC, froemken commented on Documentation/Quickstart/4-DDEV.rst
> +            --project-tld 'ddev.site' \
`ddev.site` is default

2024-07-02 19:51 UTC, froemken commented on Documentation/Quickstart/4-DDEV.rst
> +            --webserver-type 'apache-fpm' \
Just a question: Why prefer apache?

2024-07-02 20:16 UTC, froemken requested changes

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/5-TYPO3.rst
> +    .. attention::
```suggestion
    ..  attention::
```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/6-Patch-Intermezzo.rst
> +.. _quickstart-intent:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Patch

..  _quickstart-intent:
```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/6-Patch-Intermezzo.rst
> +*  Make changes to the **TypeScript/SCSS build** of TYPO3
```suggestion
*   **Fix a bug** in one of the TYPO3 Core Extensions
*   Introduce a **new feature**
*   Fix mistakes or add content in the **Documentation** of any of the Core Extensions
*   Enhance **tests** for certain functionality
*   Raise or add **dependencies** within TYPO3
*   Adjust the **TYPO3 Build** or **Testing Pipeline**
*   Make changes to the **TypeScript/SCSS build** of TYPO3
```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/6-Patch.rst
> +
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Patch

..  _quickstart-patch:

```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/6-Patch.rst
> +        cd ~/TYPO3-Contribute
Good to know you also know `cd` :-) Just kidding ;-)

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/6-Patch.rst
> +        git commit . --amend
Is the `.` really needed? Have never used it.

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/7-Contribute.rst
> +.. _quickstart-contribute:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Reviewing and more contribution

..  _quickstart-contribute:
```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/7-Contribute.rst
> +    you can always catch up the the latest `main`
```suggestion
    you can always catch up the latest `main`
```

2024-07-02 20:16 UTC, froemken commented on Documentation/Quickstart/Index.rst
> +.. _quickstart:
```suggestion
..  include:: /Includes.rst.txt

..  index::
    single: Quickstart, Kickstart

..  _quickstart:
```

2024-07-02 20:29 UTC, garvinhicking commented on Documentation/Quickstart/6-Patch.rst
> +        git commit . --amend
It's an alternate for "-a", I muscle memory this. I'll let @sbuerk decide ;)

2024-07-02 20:54 UTC, froemken approved these changes
Good work John Doe ;-)

2024-07-03 13:18 UTC, sbuerk commented on Documentation/Quickstart/6-Patch.rst
> +        git commit . --amend
The create patch intermezzo chapter splitts this by adding files with git add first. The `.` looks kind weired here, and I would more switch to `git commit -a --amend` here - or enhance the example here to to use `git add ...` to add specific files and than use only `git commit --amend` here.

Personally I use 

```
git commit --amend -a
```

through an alias - falling back to 

```
git commit --amend
```

to only commit staged files, keeping other files anstaged or make followup changes.

2024-07-03 13:22 UTC, sbuerk commented
> **Note: I couldn't get the "EXT:styleguide" Frontend Pagetree to work with this DDEV setup. Don't know if it's a bug in the styleguide setup, or a problem with ddev.**

I changed the todo in the PR and the command to generate the `sys_templtae` based frontend for now until the Site Sets issue is fixed. That makes it not so scary for contributors for now, while still mentioning something if they want to work with Site Sets.

2024-07-03 18:32 UTC, garvinhicking commented on Documentation/Quickstart/6-Patch.rst
> +        git commit . --amend
I'm fine with switching/changing this, please feel free to adjust so that it works for you!

2024-07-03 18:33 UTC, garvinhicking commented
> Really great work @garvinhicking and thank you for jumping in after a short pitch for that. That helps us a lot, I'd say.
> 
> However, pushed some minior things to slightly improve it - at least in my eyes. Hope that is fine for you !

Thank you! I think there are very many improvements to this. I did try to rework it slightly with some follow-up commits.

Let's have a chat to finalize it. Working on it together is always a win in my book, even if there are differences in the details, we can work that out :-)

2024-07-03 19:25 UTC, linawolf commented
Wow, this was a good piece of work, thanks a lot for taking care of it!

2024-07-04 07:57 UTC, sbuerk approved these changes
+1 from my side for know, will ping Benni on that pull-request if he wanna have a look before merge.

2024-07-04 08:14 UTC, sbuerk commented
Benni does not have time for it right now (we are all quite busy), but we have the approval to go on and merge it for now if we are confident. He will have a look at a later time.

So I'm goint to merge it now as a really good first improvement, and a really big thanks to garvin for the time putted into this improvement :heart: !

2024-07-04 08:16 UTC, merged